### ISSUE TITLE
Check for event already registered

### ISSUE THREAD

**Issue by futurist** [oyed/eventkeeper#1]
This lib is good for use in ES6 env, but lack a feature for query event registration status.

Could provide a query feature? like `ee.has` or some thing

Now I have to use below thing:

```
const fontSizeEvent = 'config.listFontSize'
ee.removeListeners(fontSizeEvent, true)
ee.on(fontSizeEvent, data=>{
    console.log(data)
})
```

**Comment by oyed** [comment]
Sure thing - I'll add it in tomorrow.
I've been meaning to re-visit this lib anyway, so I'll also add a few other things.
